travis:
  secure:
    BINSTAR_TOKEN: A+Gv3vGuUQq3qkaJWs3Ddm51Az1o6iuDNwhqNE3sf8lKXXI00pDgda/kc2Z+uGn0NRIJTJIHIM3aegLMduwhlxWvnKqqqnS0J2x8491aL1DM0P6xIMHVdwtc6aBO+lJzHlkSrFnkVFt17lSxEaVH8vs43uPgeErxV3UPE3ZbQTpJ7+1/QaGCE/BfahEb9YiJ4qp9HUKqIFiQgVTFw5R5MKiK0YspwDa1UH7ugcpTebz1i1GQgBx7BNrsq2FXmOOjxFUZm8SvCZSZDtJN4igjnbhhDyrT3EQ7JMAH/DXtCymhOk7VONTXFA+gLU2T1wbq6PkMeMZPnigCFFUpL0BZyX4QA8tXh+sLjxIK2NN5TNhdUtRwf4B6St2clj51XbzY64Ti/SI+ORBh1MN/tcSnFy+vEstti9qGkeCIu5ugGzKqoLOb8NMs2C5pRQcwBK/KwS43Gxfpb069qj4/uAk8kKoVXZhAYpIX5h1R77xYR+n+TgflHbwPUFB0VEf/XdwHv2Kilf6wkppVj+/eR2zGdPb8PKy0p/mzOElZj8Qhx0itRZKPfAUfKhvp3o58ReyOtD1koAiZb/wvp0LBUXNAE3GFJx19XLFw2r+fx87m9qexIAnnFMw8UHFMK6Vxed3UfEDFn+FtEA8W9moru6re2lEYF5IjDz85OPO8BrPERW4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
